### ISSUE TITLE
Broken link to eksworkshop pod yaml file in iam-role-for-serviceaccount module

### ISSUE THREAD

**Issue by sobi3ch** [Young-ook/terraform-aws-eks#113]
```
curl -LO https://eksworkshop.com/beginner/110_irsa/deploy.files/iam-pod.yaml
````
in [verify section](https://github.com/Young-ook/terraform-aws-eks/tree/caa630ac38b3da00c8495a2ed0c8b12c4dd4feaf/modules/iam-role-for-serviceaccount#verify).

Downloading redirected main page of eksworkshop.com instead of downloading `iam-pod.yaml`.

**Comment by Young-ook** [comment]
thank you for repoting!
