### ISSUE TITLE
Release 1.7.0 on terraform registry

### ISSUE THREAD

**Issue by mercuriete** [Young-ook/terraform-aws-eks#126]
Hi!

Just I noticed that the latest release on terraform is 1.6.0
https://registry.terraform.io/modules/Young-ook/eks/aws/latest

Thank you for your work.

**Comment by Young-ook** [comment]
thank you for reporting!
new version `1.7.0` is released.

**Comment by mercuriete** [comment]
Thank you very much :heart:
