### ISSUE TITLE
VPC Fallback breaks environments without a default VPC

### ISSUE THREAD

**Issue by kaecyra** [Young-ook/terraform-aws-eks#127]
The code in question:

```
## default vpc
data "aws_vpc" "default" {
  default = true
}

data "aws_subnet_ids" "default" {
  vpc_id = data.aws_vpc.default.id
}

locals {
  subnet_ids = var.subnets == null ? data.aws_subnet_ids.default.ids : var.subnets
}
```

Although var.subnets is supported and used when supplied, data.aws_vpc needs to succeed in looking up the default VPC even if custom subnets exist and are supplied, and the default is not being used. That means if the target account no longer uses the default VPC, this module cannot be used.

This is philosophical, but it feels like its reasonable to ask the user to lookup and supply their desired subnet in all cases, and fall back to their own default VPC if they elect to, in their code.

I would be willing to submit a PR to back up this request if you agree conceptually.

**Comment by Young-ook** [comment]
Agreed. 
I was already preparing a new vpc module to remove the vpc fallback code from this module.
I believe that this new submodule can support what you're saying.
* vpc module: https://github.com/Young-ook/terraform-aws-sagemaker/blob/main/modules/vpc/main.tf

FYI, this is the another terraform module code that is already replaced vpc fallback configuration with the new vpc module.
* commit history: https://github.com/Young-ook/terraform-aws-sagemaker/commit/a9b85fb78586a23781c55f4f75e5f04ddc9b3eaf#diff-9e50b8c6ad01d6004fe48435ccaf0ddd5c4e3650efb1a00f968a0fe3a55dbf61
* example: https://github.com/Young-ook/terraform-aws-sagemaker/tree/main/examples/vpc

Looks good to go.

**Comment by AzbotGithub** [comment]
@Young-ook I keep getting missing subnet exception after changing location
```
~/terraform-aws-eks/examples/fargate$ terraform plan
╷
│ Error: no matching EC2 Subnets found
│
│   with module.eks.data.aws_subnet_ids.default,
│   on .terraform/modules/eks/network.tf line 8, in data "aws_subnet_ids" "default":
│    8: data "aws_subnet_ids" "default" {
│
```
Regards

**Comment by Young-ook** [comment]
> @Young-ook I keep getting missing subnet exception after changing location
> 
> ```
> ~/terraform-aws-eks/examples/fargate$ terraform plan
> ╷
> │ Error: no matching EC2 Subnets found
> │
> │   with module.eks.data.aws_subnet_ids.default,
> │   on .terraform/modules/eks/network.tf line 8, in data "aws_subnet_ids" "default":
> │    8: data "aws_subnet_ids" "default" {
> │
> ```
> 
> Regards

Hi, please try to run with the latest version (1.7.3).
The new version will no longer look for the default vpc and subnets in your account.
This is the change log: https://github.com/Young-ook/terraform-aws-eks/releases/tag/1.7.3

Thanks.
