### ISSUE TITLE
Trying to use Container Insights on existing EKS fargate - No Pods running

### ISSUE THREAD

**Issue by TheAshwanik** [Young-ook/terraform-aws-eks#155]
Hi,

I am trying to use container insights sub module into my existing EKS fargate cluster. 
I have created 2 fargate profiles. I installed the module and ran terraform apply. 

I have enable_metrics and enable_log both as true, I see that DeamonSets are created but there is no pod running.

What am I missing please?

**Comment by Young-ook** [comment]
Hi, @TheAshwanik 
Sorry, The current version of the containerinsights submodule does not support AWS Fargate yet.
If you want to enable AWS CloudWatch Logs for Fargate, please visit this [developer guide](https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html).

Thank you.

**Comment by TheAshwanik** [comment]
> Hi, @TheAshwanik Sorry, The current version of the containerinsights submodule does not support AWS Fargate yet. If you want to enable AWS CloudWatch Logs for Fargate, please visit this [developer guide](https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html).
> 
> Thank you.

AAh ok.. Thank you.
Is'nt Fargate logging mentioned there only for application logging/log shipping.. would it work for something like container insights metrics too?
