### ISSUE TITLE
Cannot get load balancer controller example working (/examples/lb)

### ISSUE THREAD

**Issue by shpeedle** [Young-ook/terraform-aws-eks#165]
I've followed the example instructions [here](https://github.com/Young-ook/terraform-aws-eks/tree/main/examples/lb)

Everything works fine, except when I run ```kubectl -n game-2048 get ing```, the output doesn't have a url in the address column. 

My out put reads like this:

| NAME      | CLASS | HOSTS | ADDRESS | PORTS | AGE |
| ----------- | ----------- | -----------| --------------- | ----------| -------- |
| ngress-2048      | alb  | * | <no address> | 80 | 29s |

The difference on my output from the example is that I have a ```CLASS``` of ```alb``` and my ```ADDRESS``` field is empty without a URL. 

Can you help me figure out why this did not work as expected?

**Comment by Young-ook** [comment]
Hi Ben @beamsies ,
Thanks for reporting the problem. I found that fargate node has sts permission issue. So I update the load-balancer-controller example. Please try again.
