### ISSUE TITLE
Cluster autoscaler not enough RAM

### ISSUE THREAD

**Issue by mercuriete** [Young-ook/terraform-aws-eks#184]
Hi @Young-ook 

I am using your terraform module to deploy cluster autoscaler.

I am not sure when started to happen that the cluster autoscaler starts to crash due to not enough RAM

https://github.com/Young-ook/terraform-aws-eks/blob/8e9a1b2ec18f2c3459b30ab1a35fd74853ea0907/modules/cluster-autoscaler/charts/cluster-autoscaler/values.yaml#L72

Can I change the default values for your template?
in my internal eks clusters is enough with 768MiB but I wanted to customize it.

Thanks in advance.

PS: it seems it similar to what happened on 
https://github.com/Young-ook/terraform-aws-eks/commit/ea8559215ccb30d746be6778832ff8d6d64600a5
but I don't find any people with my same problem this time.

**Comment by Young-ook** [comment]
Sounds great! Make a PR or you can change the repo of helm chart by using `helm` configurations like below,
(This is just an example, the helm chart repository is NOT tested if it is valid)

```
module "cluster-autoscaler" {
  source       = "Young-ook/eks/aws//modules/cluster-autoscaler"
  oidc           = module.eks.oidc
  tags           = { env = "test" }
  helm = {
    repository  = "https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.21.0"
  }
}
```
Thank you!

**Comment by mercuriete** [comment]
Thanks!
I will try it :)
