### ISSUE TITLE
Missing audience in trust relationship irsa

### ISSUE THREAD

**Issue by mfuxi** [Young-ook/terraform-aws-eks#248]
Hi,

When creating the IRSA using the module it will not create the needed 'aud' in the trust relationship i.e:
`"oidc.eks.<REGION>.amazonaws.com/id/<OIDC-ID>:aud": "sts.amazonaws.com"` thus the serviceAccount which is created doesn't work

**Comment by Young-ook** [comment]
Thank you for bug report. I will update the irsa module to add 'aud' condition in the trusted relationship with reference to [this](https://aws.amazon.com/premiumsupport/knowledge-center/eks-troubleshoot-oidc-and-irsa/).
