### ISSUE TITLE
how to deploy aws load balancer controller in eks

### ISSUE THREAD

**Issue by reddy2018** [Young-ook/terraform-aws-eks#261]
i have my eks cluster is running, which is created with terraform. now i need to deploy aws load balancer controller in eks. 
i could not find any use full repo to deploy this.

can you please suggest anything for me

**Comment by Young-ook** [comment]
Hi,
Did you try to run blueprint example (https://github.com/Young-ook/terraform-aws-eks/tree/main/examples/blueprint)?
You can find the terraform files to deploy an eks cluster and kubernetes addons including aws-loadbalancer-contoller.

Thanks.
