### ISSUE TITLE
AWS efs csi driver support

### ISSUE THREAD

**Issue by u362eboi** [Young-ook/terraform-aws-eks#265]
Following the addons blue print example, I tried to implement the aws-efs-csi-driver from aws documentation.
https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

	
    module "helm-addons" {
      depends_on = [module.eks-addons]
      source     = "Young-ook/eks/aws//modules/helm-addons"
      version    = "2.0.3"
      tags       = local.tags
      addons = [
        {
          repository     = "https://aws.github.io/eks-charts"
          name           = "aws-load-balancer-controller"
          chart_name     = "aws-load-balancer-controller"
          namespace      = "kube-system"
          serviceaccount = "aws-load-balancer-controller"
          values = module.eks.features.fargate_enabled ? {
            "vpcId"       = var.vpc_id
            "clusterName" = module.eks.cluster.name
            } : {
            "clusterName" = module.eks.cluster.name
          }
          oidc        = module.eks.oidc
          policy_arns = [aws_iam_policy.lbc.arn]
        },
        {
          repository = "https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
          name = "aws-efs-csi-driver"
          chart_name = "aws-efs-csi-driver"
          namespace = "kube-system"
          serviceaccount = "aws-efs-csi-driver"
          oidc = module.eks.oidc
          policy_arns = [aws_iam_policy.efsc.arn]
        }
      ]
    }
	

The deployment complet with success but it seems there are some differences in the inputs of the helm modules that prevent the annotations to be created correctly for the k8s serviceaccount. None of the values = {} are pass to the Annotations, and the eks.amazonaws.com/role-arn isn't create. Here is the output of the efs-csi vs the lb.

    $ kubectl describe serviceaccount efs-csi-controller-sa --namespace kube-system
    Name:                efs-csi-controller-sa
    Namespace:           kube-system
    Labels:              app.kubernetes.io/managed-by=Helm
                         app.kubernetes.io/name=aws-efs-csi-driver
    Annotations:         meta.helm.sh/release-name: aws-efs-csi-driver
                         meta.helm.sh/release-namespace: kube-system
    Image pull secrets:  <none>
    Mountable secrets:   <none>
    Tokens:              <none>
    Events:              <none>

    $ kubectl describe serviceaccount aws-load-balancer-controller --namespace kube-system
    Name:                aws-load-balancer-controller
    Namespace:           kube-system
    Labels:              app.kubernetes.io/instance=aws-load-balancer-controller
                         app.kubernetes.io/managed-by=Helm
                         app.kubernetes.io/name=aws-load-balancer-controller
                         app.kubernetes.io/version=v2.4.7
                         helm.sh/chart=aws-load-balancer-controller-1.4.8
    Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/aws-load-balancer-controller
                         meta.helm.sh/release-name: aws-load-balancer-controller
                         meta.helm.sh/release-namespace: kube-system
    Image pull secrets:  <none>
    Mountable secrets:   <none>
    Tokens:              <none>
    Events:              <none>

Is there some way that I could use your helm module to deploy efs-csi-driver? My assumption for the parameters is comming from the code snipet in the aws doc and no manual deployment was tested yet.

    helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
        --namespace kube-system \
        --set image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/aws-efs-csi-driver \
        --set controller.serviceAccount.create=false \
        --set controller.serviceAccount.name=efs-csi-controller-sa

**Comment by Young-ook** [comment]
Hi @u362eboi,
Unfortunately, The current version of the `helm-addons` terraform module does not support customization of the irsa configuration inside the module. By default, this module sets the irsa role arn to "serviceAccount.annotations{}" helm value, but the `aws-efs-csi-driver` helm chart uses different configuration, "node.serviceAccount.annotations{}". For more information, please refer to this (https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/7666d8f1799e0dfcb8bbef4faba1139303d6f511/charts/aws-efs-csi-driver/values.yaml#L128).

Thanks.

**Comment by u362eboi** [comment]
Hi @Young-ook,
Thanks for the reply. I'll figure out an alternative.
