### ISSUE TITLE
 kubernetes-charts-incubator.storage.googleapis.com is not a valid chart

### ISSUE THREAD

**Issue by andreloc** [Young-ook/terraform-aws-eks#29]
I have just received this error while trying to test the "examples/complete". 
Using the following parameters 

module.eks.aws_eks_node_group.ng["default"]: Still creating... [2m20s elapsed]
module.eks.aws_eks_node_group.ng["default"]: Creation complete after 2m27s [id=eks-tc1:eks-tc1-default]

Error: looks like "https://kubernetes-charts-incubator.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml : 403 Forbidden
Error: failed to download "https://github.com/kubernetes/autoscaler/releases/download/cluster-autoscaler-chart-1.1.1/cluster-autoscaler-chart-1.1.1.tgz" (hint: running `helm repo update` may help)

My default file is: 

aws_region = "us-east-2"
azs        = ["us-east-2a", "us-east-2b", "us-east-2c"]
name       = "eks-tc1"
tags = {
  env  = "dev"
  test = "tc1"
}
kubernetes_version = "1.18"
managed_node_groups = [
  {
    name          = "default"
    min_size      = 1
    max_size      = 3
    desired_size  = 1
    instance_type = "t3.large"
  }
]
node_groups = [
  {
    name          = "default"
    min_size      = 1
    max_size      = 3
    desired_size  = 1
    instance_type = "t3.large"
  }
]

**Comment by andreloc** [comment]
The solution: 
https://stackoverflow.com/questions/65407317/helm-init-failed-is-not-a-valid-chart-repository-or-cannot-be-reached-failed-to

**Comment by Young-ook** [comment]
fixed
