### ISSUE TITLE
AWS account without default VPC

### ISSUE THREAD

**Issue by walczakkamil** [Young-ook/terraform-aws-eks#44]
Hello @Young-ook,

Your module is great but I have small problem on account where i don`t have default VPC.
I have working 2 VPCs on this account but without default one and i get this error after terraform plan:
Error: no matching VPC found.
On second account where we have defualt vpc configured everything is working fine.
The problem is that we can`t create additional VPC and make it default (routings, etc. ...).

Thanks
Kamil

**Comment by Young-ook** [comment]
Hi Kamil,
FYI, This module uses the default vpc for fail-safe if the user does not define the subnets to install eks on, thanks!
https://github.com/Young-ook/terraform-aws-eks/blob/64abacdc341d47dfbbd3842fee5380b59eac5772/network.tf#L13

**Comment by Young-ook** [comment]
This issues was fixed in version [1.7.3](https://github.com/Young-ook/terraform-aws-eks/releases/tag/1.7.3).
