### ISSUE TITLE
Cloudwatch insights now uses fluentbit instead of fluentd.

### ISSUE THREAD

**Issue by mercuriete** [Young-ook/terraform-aws-eks#64]
from documentation:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html

possible chart:
https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluent-bit-quickstart.yaml

I would like to know if you can implement it or if I can help you with this task.

Your project is awesome.

**Comment by Young-ook** [comment]
Hi @mercuriete , you can make a PR replacing the log agent with flientbit in helm chart of [submodule](https://github.com/Young-ook/terraform-aws-eks/tree/main/modules/container-insights/charts/container-insights).

Thank you.

**Comment by mercuriete** [comment]
ok, I will try it!

I can't tell right now if I can give hours to this project but I will try to do it anyways.
thanks

**Comment by Young-ook** [comment]
take your time.

**Comment by mercuriete** [comment]
I will leave here what I found to start implementing something:
cloudwatch metrics:
https://github.com/aws/eks-charts/tree/master/stable/aws-cloudwatch-metrics

fluentbit:
https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit

I think I will start deleting the actual code and pasting that code as starting point.
