### ISSUE TITLE
Change alb ingress controller chart to official aws

### ISSUE THREAD

**Issue by mercuriete** [Young-ook/terraform-aws-eks#98]
hi.

I saw you did an alb ingress controller on #90 

can you move that code from incubator to:

  alb_controller_helm_repo     = "https://aws.github.io/eks-charts"
  alb_controller_chart_name    = "aws-load-balancer-controller"

I think the code is here:
https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

I am using the terraform module from this guy:
https://github.com/GSA/terraform-kubernetes-aws-load-balancer-controller/blob/master/main.tf

but I would prefer to use your module.

Thanks :)

EDIT: sorry I am wrong. I read another file from alb-ingress folder

.... closing.

**Comment by Young-ook** [comment]
@mercuriete  thanks! FYI. I created a new submodule for `aws-load-balancer-controller` (https://github.com/Young-ook/terraform-aws-eks/tree/main/modules/lb-controller) and example for it (https://github.com/Young-ook/terraform-aws-eks/tree/main/examples/lb). This submodule is based on the official eks-chart.
